name: build faas release native
on:
  push:
    branches:
      - main
jobs:
  build:
    name: plugin relase package ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    concurrency:
      group: deploy-on-${{ matrix.os }}-faas   # 同一个 group 的任务会排队执行
      cancel-in-progress: true # 取消前一个任务

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-22.04,ubuntu-24.04-arm ]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '25'
          distribution: 'graalvm' # See 'Options' for all available distributions
          cache: 'maven'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'

      - name: Cache node modules admin
        uses: actions/cache@v3
        with:
          path: src/main/frontend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('src/main/frontend/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Build binary
        id: package
        run: |
          bash -e bin/package-native-github.sh /tmp/download/plugin/core/faas -Dmysql-scope='provided'
      - name: Process Linux binary
        uses: 94fzb/zrlog/.github/actions/process-artifact@11868b0b0f606f19367e69f839cddff3abf1747e
        with:
          artifact-file: ${{ steps.package.outputs.artifact_file }}
          artifact-name: ${{ steps.package.outputs.artifact_name }}
          artifact-version: ${{ steps.package.outputs.artifact_version }}
          artifact-architecture: ${{ steps.package.outputs.artifact_architecture }}
          service-url: https://webdav.zrlog.com/artifact
          service-token: ${{ secrets.ARTIFACT_SERVICE_TOKEN }}
      - name: Upload binary
        run: |
          bash -e bin/upload-bin.sh ${{ secrets.SECRET_ID }} ${{ secrets.SECRET_KEY }} ${{ secrets.BUCKET }} /tmp/download plugin ${{ secrets.HOST }}
